import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { replayFrame } from './trading-replay.mjs';
const fixture = JSON.parse(readFileSync(new URL('../data/trading-replay.json', import.meta.url)));
assert.equal(fixture.mode, 'synthetic-replay');
const at = time => fixture.bars.findIndex(bar => bar.time === time);
const initial = replayFrame(fixture, 0);
assert.equal(initial.state, 'Waiting for a signal');
assert.equal(initial.result, '—');
assert.equal(initial.events.length, 1);
assert.equal(replayFrame(fixture, at(fixture.trade.signal_bar)).state, 'Buy signal');
const open = replayFrame(fixture, at(fixture.trade.entry_bar));
assert.equal(open.state, 'Buy paper trade open');
assert.equal(open.result, '—');
assert.equal(open.events.length, 3);
const closed = replayFrame(fixture, at(fixture.trade.exit_bar));
assert.equal(closed.state, 'Paper trade closed');
assert.equal(closed.result, '132.85 USD');
assert.equal(closed.events.length, 4);
assert.equal(replayFrame(fixture, 0).events.length, 1);
assert.equal(replayFrame(fixture, 1000).bars.length, fixture.bars.length);
console.log('Replay: signal, entry, exit, reset and no premature result passed.');
