import {createVault,supported,unsupportedReason} from './local-vault.mjs';
import { useEffect,useRef,useState } from 'react';
import { Button } from './components/ui/button';
import { DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuRadioGroup,DropdownMenuRadioItem } from './components/ui/dropdown-menu';
import { ArrowLeftIcon,ChevronDownIcon } from 'lucide-react';
import { Input } from './components/ui/input';
import { Textarea } from './components/ui/textarea';
import { Label } from './components/ui/label';
import { NavigationMenu,NavigationMenuList,NavigationMenuItem,NavigationMenuLink } from './components/ui/navigation-menu';
import { Icon } from './Icon';
import { Overview } from './Overview';
import { NoteGraph } from './NoteGraph';
import { resolveLink } from '../shared/graph-model.js';
import { Preview } from './Preview';
import { NewNote,type NewRequest } from './NewNote';
import { title,excerpt,noteLinks,pages,today,week,now,workspace,workspaceName,scoped } from './notes';
import type { Note } from './types';

const route=new URLSearchParams(location.search).get('page')||'today',page=pages[route]?route:'today',config=pages[page],isSettings=page==='settings',unsupported=unsupportedReason();
export function App(){
 const [vault]=useState(()=>createVault(workspace));const [menuOpen,setMenuOpen]=useState(false),[folderName,setFolderName]=useState(''),[connecting,setConnecting]=useState(false);

 const [notes,setNotes]=useState<Note[]>([]),[active,setActive]=useState<Note|null>(null),[draft,setDraft]=useState(''),[selection,setSelection]=useState(0),[preview,setPreview]=useState(false),[saveState,setSaveState]=useState('Saved'),[saving,setSaving]=useState(false),[query,setQuery]=useState(''),[busy,setBusy]=useState(true),[loaded,setLoaded]=useState(false),[connected,setConnected]=useState(false),[feedback,setFeedback]=useState({message:'',type:'info'}),[request,setRequest]=useState<NewRequest|null>(null);
 const editor=useRef<HTMLTextAreaElement>(null),dirty=useRef(false),inFlight=useRef(false),saveRef=useRef<()=>void>(()=>{});
 const status=(message:string,type='info')=>setFeedback({message,type});
 const relevant=(n:Note)=>query.trim()?(n.path+' '+n.content).toLowerCase().includes(query.trim().toLowerCase()):page==='today'?/^(journal|inbox)\//.test(n.path):n.path.startsWith(config[2]+'/');
 async function load(){setBusy(true);try{const items=await vault.list();setNotes(items);setLoaded(true);setConnected(true);return items;}catch(e){setConnected(false);throw e;}finally{setBusy(false);}}
 async function connect(reconnect=false){if(connecting||inFlight.current||(!reconnect&&!canLeave()))return;setConnecting(true);try{if(reconnect)await vault.reconnect();else await vault.connect();setFolderName(vault.name);if(!reconnect){setActive(null);setDraft('');setNotes([]);setLoaded(false);dirty.current=false;setSelection(v=>v+1);}const items=await load();status('Folder connected. Notes stay on this computer.','success');if(items.length&&(!reconnect||!active))select(items[0],true);}catch(e){if(e instanceof Error&&e.name==='NotAllowedError')setConnected(false);status(e instanceof Error?(e.name==='AbortError'?'Folder selection cancelled. Your current folder and draft are unchanged.':e.message):'Unable to open this folder. Try again.','error');}finally{setConnecting(false);}}
 async function disconnect(){if(!canLeave()||connecting)return;setConnecting(true);try{await vault.forget();setFolderName('');setConnected(false);setLoaded(false);setNotes([]);setActive(null);setDraft('');dirty.current=false;status('Folder forgotten in this browser. Files were not deleted.');}finally{setConnecting(false);}}

 function canLeave(){if(connecting){status('Wait for the folder operation to finish.');return false;}if(inFlight.current){status('Wait for the save to finish before continuing.');return false;}return !dirty.current||confirm('Leave without saving this draft? Choose Cancel to keep editing.');}
 function select(n:Note,checked=false){if(!checked&&!canLeave())return false;setActive({...n});setDraft(n.content);setSelection(v=>v+1);dirty.current=false;setSaveState(n.version===null?'New draft':'Saved');return true;}
 function openNew(kind=config[2],name='',opener=document.activeElement as HTMLElement){if(!connected){status('Connect a folder before creating a note.');return;}setRequest({kind,name,opener});}
 async function save(){if(!active||inFlight.current||connecting)return;inFlight.current=true;setSaving(true);setSaveState('Saving...');const content=editor.current?.value??draft,note=active;try{const data=await vault.save({...note,content});setActive({...note,content,version:data.version});dirty.current=editor.current?.value!==content;setSaveState(dirty.current?'Unsaved changes':'Saved to your vault');try{await load();status('Note saved.','success');}catch{status('Note saved. The note list could not refresh. Reconnect the folder and retry.','error');}}catch(e){if(e instanceof Error&&e.name==='NotAllowedError')setConnected(false);setSaveState('Not saved. Draft kept in this tab.');status(e instanceof Error?e.message:'Save failed. Your draft is still in this tab.','error');}finally{inFlight.current=false;setSaving(false);}}

 saveRef.current=()=>void save();
 useEffect(()=>{document.title=`${config[0]} / ${workspaceName} / KWG`;let live=true;void (async()=>{if(!supported()){setBusy(false);return [];}const ready=await vault.restore();setFolderName(vault.name);if(!ready){setBusy(false);return [];}return load();})().then(items=>{if(!live)return;const requested=new URLSearchParams(location.search).get('note');const preferred=requested?items.find(n=>n.path===requested):items.find(n=>n.path===(page==='today'?`journal/${today}.md`:page==='review'?`reviews/Week of ${week}.md`:''))||items.find(relevant);if(preferred)select(preferred,true);if(requested&&!preferred)status('The requested note was not found. Search the vault or create a new note.','error');}).catch(()=>{if(live)status('Cannot access this folder. Reconnect it or choose another folder.','error');});
 const unload=(e:BeforeUnloadEvent)=>{if(dirty.current){e.preventDefault();}},key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();saveRef.current();}},offline=()=>{status('The network is offline. This open page can still edit your connected local folder.');};window.addEventListener('beforeunload',unload);document.addEventListener('keydown',key);window.addEventListener('offline',offline);return()=>{live=false;window.removeEventListener('beforeunload',unload);document.removeEventListener('keydown',key);window.removeEventListener('offline',offline);};},[]);
 async function reload(){if(!active||!canLeave())return;try{const items=await load(),n=items.find(n=>n.path===active.path);if(n){select(n,true);status('Loaded the latest file.');}else status('This draft has not been saved yet.');}catch{status('Cannot reload the note. Your draft is still in this tab. Reconnect the folder and retry.','error');}}
 function linked(name:string){const resolved=resolveLink(notes,active?.path||'',name);if(resolved)select(resolved);else status(`"${name}" is missing or matches more than one note. Use a folder-qualified link or create the missing note.`);}

 const backlinks=active?notes.filter(n=>n.path!==active.path&&noteLinks(n).some((l:string)=>resolveLink(notes,n.path,l)?.path===active.path)):[],list=notes.filter(relevant);

 return <><a className="skip" href="#main">Skip to workspace</a><aside className="sidebar" data-menu-open={menuOpen}><Button asChild variant="outline" className="vault-return"><a href="/vault"><ArrowLeftIcon aria-hidden="true"/>Back to vault</a></Button><a className="brand" href={scoped('/today')} aria-label="Dashboard home"><span className="brand-symbol" aria-hidden="true"><i/><i/><i/><i/></span><span>KWG<small>{workspaceName} workspace</small></span></a><Button id="pages-toggle" variant="outline" className="pages-toggle" aria-expanded={menuOpen} aria-controls="workspace-navigation" onKeyDown={e=>{if(e.key==='Escape')setMenuOpen(false);}} onClick={()=>setMenuOpen(!menuOpen)}><Icon name="layers"/>Pages<ChevronDownIcon aria-hidden="true"/></Button><p className="nav-label">Pages</p><NavigationMenu id="workspace-navigation" aria-label="Workspace" orientation="vertical" viewport={false}><NavigationMenuList>{Object.entries(pages).map(([id,[label,,,icon]])=><NavigationMenuItem key={id}><NavigationMenuLink href={scoped('/'+id)} active={page===id} aria-current={page===id?'page':undefined} onKeyDown={e=>{if(e.key==='Escape'){setMenuOpen(false);document.querySelector<HTMLButtonElement>('#pages-toggle')?.focus();}}}><Icon name={icon}/>{label}</NavigationMenuLink></NavigationMenuItem>)}</NavigationMenuList></NavigationMenu><div className="rail-bottom"><span><Icon name="folder"/></span><h3>Local vault</h3><p>Your notes stay on this computer.</p><a href={scoped('/knowledge')}>Browse notes</a></div><div className="workspace-switch"><span id="workspace-label" className="workspace-switch-label">Workspace</span><DropdownMenu><DropdownMenuTrigger id="workspace-select" data-workspace={workspace} aria-labelledby="workspace-label workspace-current" render={<Button variant="outline" className="workspace-trigger"/>}><span id="workspace-current">{workspaceName}</span><ChevronDownIcon aria-hidden="true"/></DropdownMenuTrigger><DropdownMenuContent aria-labelledby="workspace-label"><DropdownMenuRadioGroup aria-labelledby="workspace-label" value={workspace} onValueChange={next=>{if(next===workspace||!canLeave())return;dirty.current=false;location.assign('/vault/dashboard?page='+page+'&workspace='+next);}}><DropdownMenuRadioItem data-workspace="personal" value="personal">Personal</DropdownMenuRadioItem><DropdownMenuRadioItem data-workspace="parallel" value="parallel">Parallel</DropdownMenuRadioItem></DropdownMenuRadioGroup></DropdownMenuContent></DropdownMenu></div></aside>
 <main id="main" tabIndex={-1}><header className="topbar"><div className="breadcrumb">Workspace <span aria-hidden="true">/</span> <strong id="breadcrumb">{config[0]}</strong></div><div className="top-actions"><span id="connection" className={'connection'+(connected?'':' offline')}>{connected?'Local folder connected':'Folder not connected'}</span>{!isSettings&&<Button id="capture" variant="outline" aria-label="Quick capture" disabled={!connected} onClick={e=>openNew('inbox','',e.currentTarget)}><Icon name="plus"/>Quick capture</Button>}</div></header>
 <section className="intro"><div>{!isSettings&&<p id="eyebrow">{now.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'})}</p>}<h1 id="heading">{config[0]}</h1><p id="subtitle">{config[1]}</p></div>{!isSettings&&<Button id="create" disabled={!connected} onClick={e=>openNew(config[2],page==='journal'||page==='today'?today:page==='review'?`Week of ${week}`:'',e.currentTarget)}><Icon name="plus"/>New note</Button>}</section>
 {isSettings?<section id="settings" aria-busy={busy} className="folder-panel" aria-label="Local folder access"><h2>{folderName?workspaceName+' folder: '+folderName:'Connect your '+workspaceName+' folder'}</h2><p>{unsupported==='insecure'?'Folder access needs a secure page. Open this dashboard over HTTPS, or on localhost for development. No notes have been read.':unsupported==='brave'?<>Brave turns off folder access by default. To use this dashboard in Brave, open <code>brave://flags/#file-system-access-api</code>, set it to Enabled, then relaunch Brave. Or use a current desktop Edge or Chrome. No notes have been read.</>:unsupported?'This browser cannot edit local folders here. Use a current desktop Edge or Chrome browser over HTTPS or localhost. No notes have been read.':'Choose the vault folder for this workspace. Only journal, knowledge, projects, reviews, founder and inbox are read. Saves go to that folder; previous versions go to .history. No notes are uploaded.'}</p><div className="folder-actions"><Button variant="outline" disabled={!supported()||connecting||saving} onClick={()=>void connect()}>{connecting?'Opening folder...':folderName?'Choose another folder':'Choose folder'}</Button>{folderName&&<><Button variant="outline" disabled={connecting||saving} onClick={()=>void connect(true)}>Reconnect folder</Button><Button variant="outline" disabled={connecting||saving} onClick={()=>void disconnect().catch(()=>status('Could not forget this folder. Try again.','error'))}>Forget folder</Button></>}</div><div className="folder-privacy"><h3>Access and privacy</h3><p>Choose only a vault folder you trust this site to access. Folder permissions belong to this website origin. Only the six named folders are read, without subfolders. Notes over 1 MiB and unsupported filenames are skipped. Forget folder removes its remembered handle; revoke access in browser site settings.</p></div></section>:<>
 <section id="overview" aria-label="Page overview" aria-busy={busy}>{loaded?<><Overview notes={notes} page={page} onNew={openNew}/>{page==='knowledge'&&<NoteGraph notes={notes} activePath={active?.path||null} onOpen={path=>{const n=notes.find(n=>n.path===path);if(!n||!select(n))return false;setPreview(false);requestAnimationFrame(()=>{editor.current?.scrollIntoView({block:'start'});editor.current?.focus({preventScroll:true});});return true;}}/>}</>:busy?<div className="loading-panel">Loading your workspace...</div>:<div className="loading-panel"><div className="connection-copy"><h2>No folder connected</h2><p>{unsupported?'Folder access is not available in this browser. Open Settings for setup instructions.':'Choose a vault folder in Settings, or reconnect its saved permission.'}</p></div><Button asChild variant="outline"><a href={scoped('/settings')}>Open Settings</a></Button></div>}</section>
 <section className="section-heading"><div><h2 id="library-heading">{page==='today'?'Journal and inbox':page==='projects'?'Project notes':`${config[0]} notes`}</h2><p id="library-description">Select a note to read or edit.</p></div><span className="shortcut">Ctrl + S to save</span></section><div className="workspace"><section className="library" aria-label="Notes"><Label htmlFor="search">Search this workspace</Label><div className="search-field"><span><Icon name="search"/></span><Input id="search" type="search" placeholder="Title, text, or folder" aria-describedby="search-help" onInput={e=>setQuery(e.currentTarget.value)}/></div><p id="search-help">Search covers every section in {workspaceName}.</p><div className="list-caption"><span id="list-label">{query.trim()?'Search results':'Recent notes'}</span><span id="list-count">{list.length}</span></div><div id="notes">{list.length?list.map(n=><Button variant="ghost" key={n.path} className={`note ${active?.path===n.path?'selected':''}`} data-path={n.path} aria-pressed={active?.path===n.path} onClick={()=>select(n)}><b>{title(n)}</b><span className="note-excerpt">{excerpt(n)}</span><small>{n.path.split('/')[0]} / {new Date(n.modified).toLocaleDateString()}</small></Button>):<p className="list-empty">{query.trim()?'No notes match your search. Try a different word.':'No notes in this section. Use New note to add one.'}</p>}</div></section>
 <section className="writing" aria-label="Note editor"><div id="empty" hidden={!!active}><span className="empty-illustration" aria-hidden="true"><Icon name="book"/></span><h2>No note selected</h2><p>Create a note or select one from the list.</p><Button variant="outline" id="empty-create" disabled={!connected} onClick={e=>openNew(config[2],'',e.currentTarget)}>Create a note</Button><div className="writing-tips"><span><Icon name="link"/>Link notes with [[Note title]]</span><span><Icon name="save"/>Save changes to keep your draft</span></div></div>
 <div id="editor" hidden={!active}><div className="editor-top"><span className="file-type"><Icon name="file"/>Markdown note</span><Button id="preview-toggle" variant="outline" aria-pressed={preview} onClick={()=>{setDraft(editor.current?.value??draft);setPreview(!preview);}}>{preview?'Edit':'Preview'}</Button></div><p id="note-path">{active?.path}</p><Label htmlFor="content" className="sr-only">Markdown note content</Label><Textarea key={selection} ref={editor} id="content" defaultValue={draft} spellCheck aria-describedby="save-state" hidden={preview} onInput={e=>{setDraft(e.currentTarget.value);dirty.current=true;setSaveState('Unsaved changes');}}/><article id="preview" hidden={!preview}><Preview content={draft} onLink={linked}/></article><footer className="editor-footer"><div><span id="save-state" role="status">{saveState}</span><small id="word-count">{draft.trim()?draft.trim().split(/\s+/).length:0} words</small></div><div className="editor-buttons"><Button id="reload" variant="outline" onClick={()=>void reload()}>Reload</Button><Button id="save" disabled={saving} onClick={()=>void save()}>{saving?'Saving...':'Save note'}</Button></div></footer><section id="backlinks" aria-label="Backlinks"><strong>Linked from</strong> {backlinks.length?backlinks.map(n=><a key={n.path} href="#" data-path={n.path} onClick={e=>{e.preventDefault();select(n);}}>{title(n)} </a>):'No other notes link here yet.'}</section></div></section></div></>}
 <div id="feedback" className={'feedback '+feedback.type} hidden={!feedback.message}><p id="status" role="status" aria-live="polite">{feedback.message}</p><Button id="retry" variant="outline" hidden={connected||!folderName||isSettings} onClick={()=>void connect(true)}>Reconnect folder</Button></div><footer className="page-footer"><span>{workspaceName} dashboard</span><span>Markdown files on your computer</span></footer></main>
 <NewNote request={request} notes={notes} onClose={()=>setRequest(null)} onCreate={n=>{if(!select(n))return false;dirty.current=true;setSaveState('New draft. Save to keep it.');setPreview(false);return true;}}/>
 </>;
}
