import {createVault,supported,unsupportedReason} from './local-vault.mjs';
import { useEffect,useRef,useState } from 'react';
import { ArrowLeftIcon,MenuIcon } from 'lucide-react';
import { Icon } from './Icon';
import { Overview } from './Overview';
import { NoteGraph } from './NoteGraph';
import { MilestoneBadge } from './Goal';
import { WorkspaceMenu } from './WorkspaceMenu';
import { resolveLink } from '../shared/graph-model.js';
import { Preview } from './Preview';
import { NewNote,type NewRequest } from './NewNote';
import { title,excerpt,noteLinks,pages,today,week,now,workspace,workspaceName,scoped } from './notes';
import type { Note } from './types';

const route=new URLSearchParams(location.search).get('page')||'today',page=pages[route]?route:'today',config=pages[page],isSettings=page==='settings',unsupported=unsupportedReason();
export function App(){
 const [vault]=useState(()=>createVault(workspace));const [menuOpen,setMenuOpen]=useState(false),[folderName,setFolderName]=useState(''),[connecting,setConnecting]=useState(false);

 const [notes,setNotes]=useState<Note[]>([]),[active,setActive]=useState<Note|null>(null),[draft,setDraft]=useState(''),[selection,setSelection]=useState(0),[preview,setPreview]=useState(false),[saveState,setSaveState]=useState('Saved'),[saving,setSaving]=useState(false),[query,setQuery]=useState(''),[busy,setBusy]=useState(true),[loaded,setLoaded]=useState(false),[connected,setConnected]=useState(false),[feedback,setFeedback]=useState({message:'',type:'info'}),[request,setRequest]=useState<NewRequest|null>(null);
 const editor=useRef<HTMLTextAreaElement>(null),dirty=useRef(false),inFlight=useRef(false),saveRef=useRef<()=>void>(()=>{});
 const status=(message:string,type='info')=>setFeedback({message,type});
 const relevant=(n:Note)=>query.trim()?(n.path+' '+n.content).toLowerCase().includes(query.trim().toLowerCase()):page==='today'?/^(journal|inbox)\//.test(n.path):n.path.startsWith(config[1]+'/');
 async function load(){setBusy(true);try{const items=await vault.list();setNotes(items);setLoaded(true);setConnected(true);return items;}catch(e){setConnected(false);throw e;}finally{setBusy(false);}}
 async function connect(reconnect=false){if(connecting||inFlight.current||(!reconnect&&!canLeave()))return;setConnecting(true);try{if(reconnect)await vault.reconnect();else await vault.connect();setFolderName(vault.name);if(!reconnect){setActive(null);setDraft('');setNotes([]);setLoaded(false);dirty.current=false;setSelection(v=>v+1);}const items=await load();status('Folder connected.','success');if(items.length&&(!reconnect||!active))select(items[0],true);}catch(e){if(e instanceof Error&&e.name==='NotAllowedError')setConnected(false);status(e instanceof Error?(e.name==='AbortError'?'Selection cancelled.':e.message):'Cannot open folder.','error');}finally{setConnecting(false);}}
 async function disconnect(){if(!canLeave()||connecting)return;setConnecting(true);try{await vault.forget();setFolderName('');setConnected(false);setLoaded(false);setNotes([]);setActive(null);setDraft('');dirty.current=false;status('Folder forgotten.');}finally{setConnecting(false);}}

 function canLeave(){if(connecting){status('Folder busy.');return false;}if(inFlight.current){status('Saving. Wait.');return false;}return !dirty.current||confirm('Discard unsaved draft?');}
 function select(n:Note,checked=false){if(!checked&&!canLeave())return false;setActive({...n});setDraft(n.content);setSelection(v=>v+1);dirty.current=false;setSaveState(n.version===null?'New draft':'Saved');return true;}
 function openNew(kind=config[1],name='',opener=document.activeElement as HTMLElement,template?:string){if(!connected){status('Connect a folder first.');return;}setRequest({kind,name,opener,template});}
 async function save(){if(!active||inFlight.current||connecting)return;inFlight.current=true;setSaving(true);setSaveState('Saving...');const content=editor.current?.value??draft,note=active;try{const data=await vault.save({...note,content});setActive({...note,content,version:data.version});dirty.current=editor.current?.value!==content;setSaveState(dirty.current?'Unsaved changes':'Saved');try{await load();status('Note saved.','success');}catch{status('Saved. List not refreshed.','error');}}catch(e){if(e instanceof Error&&e.name==='NotAllowedError')setConnected(false);setSaveState('Not saved');status(e instanceof Error?e.message:'Not saved.','error');}finally{inFlight.current=false;setSaving(false);}}

 saveRef.current=()=>void save();
 useEffect(()=>{document.title=`${config[0]} / ${workspaceName} / KWG`;let live=true;void (async()=>{if(!supported()){setBusy(false);return [];}const ready=await vault.restore();setFolderName(vault.name);if(!ready){setBusy(false);return [];}return load();})().then(items=>{if(!live)return;const requested=new URLSearchParams(location.search).get('note');const preferred=requested?items.find(n=>n.path===requested):items.find(n=>n.path===(page==='today'?`journal/${today}.md`:page==='review'?`reviews/Week of ${week}.md`:''))||items.find(relevant);if(preferred)select(preferred,true);if(requested&&!preferred)status('Note not found.','error');}).catch(()=>{if(live)status('Cannot access folder.','error');});
 const unload=(e:BeforeUnloadEvent)=>{if(dirty.current){e.preventDefault();}},key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();saveRef.current();}},offline=()=>{status('Offline.');};window.addEventListener('beforeunload',unload);document.addEventListener('keydown',key);window.addEventListener('offline',offline);return()=>{live=false;window.removeEventListener('beforeunload',unload);document.removeEventListener('keydown',key);window.removeEventListener('offline',offline);};},[]);
 async function reload(){if(!active||!canLeave())return;try{const items=await load(),n=items.find(n=>n.path===active.path);if(n){select(n,true);status('Reloaded.');}else status('Not saved yet.');}catch{status('Cannot reload.','error');}}
 function linked(name:string){const resolved=resolveLink(notes,active?.path||'',name);if(resolved)select(resolved);else status(`No single note "${name}".`);}

 const backlinks=active?notes.filter(n=>n.path!==active.path&&noteLinks(n).some((l:string)=>resolveLink(notes,n.path,l)?.path===active.path)):[],list=notes.filter(relevant);


 const closeMenu=()=>{setMenuOpen(false);document.querySelector<HTMLButtonElement>('#pages-toggle')?.focus();};
 const muted='text-base-content/70';
 useEffect(()=>{if(!menuOpen)return;const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();closeMenu();}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[menuOpen]);
 return <div className="drawer lg:drawer-open">
 <input id="pages-drawer" type="checkbox" className="drawer-toggle" tabIndex={-1} aria-hidden="true" checked={menuOpen} onChange={e=>setMenuOpen(e.currentTarget.checked)}/>
 <div className="drawer-content min-w-0">
 <a className="skip" href="#main">Skip to workspace</a>
 <main id="main" tabIndex={-1} className="mx-auto w-full max-w-6xl px-4 sm:px-6 lg:px-10">
 <header className="topbar flex min-h-16 flex-wrap items-center justify-between gap-3 border-b border-base-300 py-3">
  <div className="flex min-w-0 items-center gap-3"><button id="pages-toggle" type="button" className="btn btn-outline lg:hidden" aria-expanded={menuOpen} aria-controls="workspace-navigation" onClick={()=>{const next=!menuOpen;setMenuOpen(next);if(next)requestAnimationFrame(()=>document.querySelector<HTMLElement>('#workspace-navigation a[aria-current=page]')?.focus());}}><MenuIcon aria-hidden="true" className="size-4"/>Pages</button>
  <nav className="breadcrumbs min-w-0 pe-1 text-sm" aria-label="Breadcrumb"><ul><li className={muted}>Workspace</li><li><strong id="breadcrumb" className="font-semibold">{config[0]}</strong></li></ul></nav></div>
  <div className="top-actions flex flex-wrap items-center gap-3"><span id="connection" className={'badge badge-soft '+(connected?'badge-success':'badge-error')}>{connected?'Local folder connected':'Folder not connected'}</span>{!isSettings&&<button id="capture" type="button" className="btn btn-outline btn-sm" aria-label="Quick capture" disabled={!connected} onClick={e=>openNew('inbox','',e.currentTarget)}><Icon name="plus"/>Quick capture</button>}</div>
 </header>
 <section className="intro flex flex-col items-start justify-between gap-4 pt-8 pb-6 sm:flex-row sm:items-end"><div className="min-w-0">{!isSettings&&<p id="eyebrow" className={'mb-1 text-sm '+muted}>{now.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'})}</p>}<h1 id="heading" className="leading-tight">{config[0]}</h1></div>{!isSettings&&<button id="create" type="button" className="btn btn-primary" disabled={!connected} onClick={e=>openNew(config[1],page==='journal'||page==='today'?today:page==='review'?`Week of ${week}`:'',e.currentTarget)}><Icon name="plus"/>New note</button>}</section>
 {isSettings?<section id="settings" aria-busy={busy} className="folder-panel card mb-6 max-w-3xl border border-base-300 bg-base-200" aria-label="Local folder access"><div className="card-body gap-4 p-5 sm:p-6"><h2 className="text-base font-semibold leading-6">{folderName||'No folder'}</h2>{unsupported&&<p className={muted}>{unsupported==='insecure'?'Needs HTTPS or localhost.':unsupported==='brave'?<>Enable <code className="font-mono">brave://flags/#file-system-access-api</code>, then relaunch.</>:'Use desktop Chrome or Edge.'}</p>}<div className="folder-actions flex flex-col gap-3 sm:flex-row sm:flex-wrap"><button type="button" className="btn btn-primary" disabled={!supported()||connecting||saving} onClick={()=>void connect()}>{connecting?'Opening folder...':folderName?'Choose another folder':'Choose folder'}</button>{folderName&&<><button type="button" className="btn btn-outline" disabled={connecting||saving} onClick={()=>void connect(true)}>Reconnect folder</button><button type="button" className="btn btn-outline" disabled={connecting||saving} onClick={()=>void disconnect().catch(()=>status('Cannot forget folder.','error'))}>Forget folder</button></>}</div></div></section>:<>
 <section id="overview" aria-label="Page overview" aria-busy={busy}>{loaded?<><Overview notes={notes} page={page} onNew={openNew}/>{page==='knowledge'&&<NoteGraph notes={notes} activePath={active?.path||null} onOpen={path=>{const n=notes.find(n=>n.path===path);if(!n||!select(n))return false;setPreview(false);requestAnimationFrame(()=>{editor.current?.scrollIntoView({block:'start'});editor.current?.focus({preventScroll:true});});return true;}}/>}</>:busy?<div className={'loading-panel card border border-base-300 bg-base-200 p-6 '+muted}><span className="loading loading-spinner loading-sm" role="status" aria-label="Loading"/></div>:<div className="loading-panel card flex flex-col items-start justify-between gap-4 border border-base-300 bg-base-200 p-5 sm:flex-row sm:items-center sm:p-6"><div className="connection-copy min-w-0"><h2>{unsupported?'Browser not supported':'No folder connected'}</h2></div><a className="btn btn-outline" href={scoped('/settings')}>Open Settings</a></div>}</section>
 <section className="section-heading mt-10 mb-4 flex items-end justify-between gap-4"><h2 id="library-heading">{page==='today'?'Journal and inbox':page==='projects'?'Project notes':`${config[0]} notes`}</h2></section>
 <div className="workspace card grid overflow-hidden border border-base-300 bg-base-200 md:grid-cols-[18rem_minmax(0,1fr)]">
  <section className="library min-w-0 border-b border-base-300 bg-base-100 p-5 md:border-r md:border-b-0 md:p-6" aria-label="Notes"><label htmlFor="search" className="sr-only">Search</label><label className="search-field input w-full"><Icon name="search"/><input id="search" type="search" className="grow" placeholder="Search" onInput={e=>setQuery(e.currentTarget.value)}/></label><div className={'list-caption mt-4 mb-3 flex justify-between text-xs '+muted}><span id="list-label">{query.trim()?'Search results':'Recent notes'}</span><span id="list-count" className="badge badge-ghost badge-sm">{list.length}</span></div><div id="notes" className="grid gap-1">{list.length?list.map(n=><button type="button" key={n.path} className={'note block w-full min-w-0 rounded-field border px-4 py-3 text-left hover:bg-base-300 '+(active?.path===n.path?'selected border-primary bg-base-300':'border-transparent')} data-path={n.path} aria-pressed={active?.path===n.path} onClick={()=>select(n)}><b className="text-sm font-semibold">{title(n)}</b><span className={'note-excerpt mt-1 text-xs '+muted}>{excerpt(n)}</span><small className={'mt-1 text-xs '+muted}>{n.path.split('/')[0]} / {new Date(n.modified).toLocaleDateString()}</small></button>):<p className={'list-empty py-3 text-sm leading-relaxed '+muted}>{query.trim()?'No matches':'No notes'}</p>}</div></section>
  <section className="writing min-w-0 p-5 md:p-6" aria-label="Note editor"><div id="empty" hidden={!!active} className="flex min-h-80 flex-col items-center justify-center gap-3 text-center"><span className="empty-illustration grid size-12 place-items-center rounded-box bg-base-300 text-primary" aria-hidden="true"><Icon name="book"/></span><h2>No note selected</h2><button type="button" className="btn btn-outline" id="empty-create" disabled={!connected} onClick={e=>openNew(config[1],'',e.currentTarget)}>Create a note</button></div>
  <div id="editor" hidden={!active}><div className="editor-top flex items-center justify-between gap-3"><span/><button id="preview-toggle" type="button" className="btn btn-outline btn-sm" aria-pressed={preview} onClick={()=>{setDraft(editor.current?.value??draft);setPreview(!preview);}}>{preview?'Edit':'Preview'}</button></div><p id="note-path" className={'my-3 text-xs break-all '+muted}>{active?.path}</p><label htmlFor="content" className="sr-only">Markdown note content</label><textarea key={selection} ref={editor} id="content" className="textarea w-full resize-y" defaultValue={draft} spellCheck aria-describedby="save-state" hidden={preview} onInput={e=>{setDraft(e.currentTarget.value);dirty.current=true;setSaveState('Unsaved changes');}}/><article id="preview" className="py-4" hidden={!preview}><Preview content={draft} onLink={linked}/></article><footer className="editor-footer mt-4 flex flex-wrap items-center justify-between gap-4 border-t border-base-300 pt-4"><div><span id="save-state" role="status" className={'text-xs '+muted}>{saveState}</span><small id="word-count" className={'mt-1 block text-xs '+muted}>{draft.trim()?draft.trim().split(/\s+/).length:0} words</small></div><div className="editor-buttons flex w-full gap-2 sm:w-auto"><button id="reload" type="button" className="btn btn-outline flex-1 sm:flex-none" onClick={()=>void reload()}>Reload</button><button id="save" type="button" className="btn btn-primary flex-1 sm:flex-none" disabled={saving} onClick={()=>void save()}>{saving?'Saving...':'Save note'}</button></div></footer><section id="backlinks" className={'mt-6 text-xs '+muted} aria-label="Backlinks"><strong>Linked from</strong> {backlinks.length?backlinks.map(n=><a key={n.path} href="#" className="link mr-3 inline-flex min-h-11 items-center" data-path={n.path} onClick={e=>{e.preventDefault();select(n);}}>{title(n)} </a>):'None'}</section></div></section>
 </div></>}
 <div id="feedback" className={'feedback alert alert-soft my-4 flex-col items-start sm:flex-row sm:items-center sm:justify-between '+(feedback.type==='error'?'alert-error':feedback.type==='success'?'alert-success':'')} hidden={!feedback.message}><p id="status" role="status" aria-live="polite">{feedback.message}</p><button id="retry" type="button" className="btn btn-outline btn-sm" hidden={connected||!folderName||isSettings} onClick={()=>void connect(true)}>Reconnect folder</button></div>
 <div className="h-12"/></main>
 </div>
 <div className="drawer-side z-40">
 <label htmlFor="pages-drawer" aria-label="Close pages" className="drawer-overlay"/>
 <aside className="sidebar flex min-h-full flex-col gap-5 border-r border-base-300 bg-base-200 px-4 py-5" data-menu-open={menuOpen}>
  <a className="vault-return btn btn-outline btn-block justify-start" href="/vault"><ArrowLeftIcon aria-hidden="true" className="size-4"/>Back to vault</a>
  <a className="brand flex items-center gap-3 px-2 text-2xl font-bold" href={scoped('/today')} aria-label="Dashboard home"><span className="brand-symbol" aria-hidden="true"><i/><i/><i/><i/></span><span>KWG<small className={'mt-1 block text-xs font-normal '+muted}>{workspaceName} workspace</small></span></a>
  <MilestoneBadge/>
  <nav id="workspace-navigation" aria-label="Workspace"><ul className="menu w-full gap-0.5 p-0">{Object.entries(pages).map(([id,[label,,icon]])=><li key={id}><a className={'min-h-11 '+(page===id?'menu-active':'')} href={scoped('/'+id)} aria-current={page===id?'page':undefined}><Icon name={icon}/>{label}</a></li>)}</ul></nav>
  <div className="mt-auto"/>
  <WorkspaceMenu canLeave={()=>canLeave()} onLeave={()=>{dirty.current=false;}} page={page}/>
 </aside></div>
 <NewNote request={request} notes={notes} onClose={()=>setRequest(null)} onCreate={n=>{if(!select(n))return false;dirty.current=true;setSaveState('New draft. Save to keep it.');setPreview(false);return true;}}/>
 </div>;
}
