import type { ReactNode } from 'react';
import { Button } from './components/ui/button';
import { Icon } from './Icon';
import { dateKey,now,today,monday,week,title,excerpt,linkTo,noteLinks,scoped } from './notes';
import { taskRows as rawTasks, reviewFindings } from '../shared/vault-model.js';
import type { Note } from './types';

const taskRows=rawTasks as (notes:Note[])=>{done:boolean;text:string;note:Note;due:string|null}[];
export function Overview({notes,page,onNew}:{notes:Note[];page:string;onNew:(kind:string,name?:string,opener?:HTMLElement)=>void}) {
 const group=(folder:string)=>notes.filter(n=>n.path.startsWith(folder+'/'));
 const projects=group('projects'),journals=group('journal'),knowledge=group('knowledge'),inbox=group('inbox'),daily=notes.find(n=>n.path===`journal/${today}.md`);
 const row=(n:Note)=><a key={n.path} className="note-row" href={linkTo(n)}><Icon name="file"/><span>{title(n)}<small>{n.path.split('/')[0]} / {new Date(n.modified).toLocaleDateString()}</small></span></a>;
 const start=(kind:string,name:string,label:string)=><Button variant="outline" className="secondary" onClick={e=>onNew(kind,name,e.currentTarget)}>{label}</Button>;
 const quick=(url:string,name:string,detail:string,type:string)=><a className="quick-card" href={scoped(url)}><span className="icon-box"><Icon name={type}/></span><span><strong>{name}</strong><small>{detail}</small></span><span className="arrow"><Icon name="arrow"/></span></a>;
 const days=Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(d.getDate()+i);const key=dateKey(d);return {d,key,saved:notes.some(n=>n.path===`journal/${key}.md`)};});
 const activity=<section className="panel"><div className="panel-head"><h2>This week</h2><Icon name="check"/></div><div className="week-strip">{days.map(({d,key,saved})=><div key={key} className={`day ${key===today?'current':''} ${saved?'has-entry':''}`} aria-label={`${key}, ${saved?'entry saved':'no dated entry'}`}><span>{d.toLocaleDateString('en',{weekday:'short'})}</span><strong>{d.getDate()}</strong><span className="day-dot" aria-hidden="true"/></div>)}</div><div className="small-stat"><strong>{days.filter(d=>d.saved).length} / 7</strong><span>days with a dated journal entry</span></div><div className="panel-foot"><span>Week of {week}</span><a className="text-link" href={scoped('/review')}>Review week</a></div></section>;
 const dailyPanel=<section className="panel daily-panel"><div className="panel-head"><h2>Daily entry</h2><span className={`pill ${daily?'success':''}`}>{daily?'Saved':'Not started'}</span></div><div className="daily-layout"><div className="date-tile"><span>{now.toLocaleDateString('en',{month:'short'})}</span><strong>{now.getDate()}</strong></div><div><h3>{daily?"Continue today's entry":"Write today's entry"}</h3><p>{daily?excerpt(daily).slice(0,180):'Set an intention, record what happened, and note what you learned.'}</p>{daily?<Button asChild variant="outline" className="secondary"><a href={linkTo(daily)}>Open entry <Icon name="arrow"/></a></Button>:start('journal',today,'Start daily entry')}</div></div><div className="panel-foot"><span>Daily reflection</span><span>Saved as Markdown</span></div></section>;
 const shortcuts=<div className="quick-actions">{quick('/projects','Projects',`${projects.length} project notes`,'layers')}{quick('/knowledge','Knowledge',`${knowledge.length} ${knowledge.length===1?'note':'notes'} in your library`,'network')}{quick('/review','Weekly review','Review entries and next actions','check')}</div>;
 let content:ReactNode;
 if(page==='today')content=<><div className="dashboard-grid">{dailyPanel}{activity}</div>{shortcuts}</>;
 if(page==='journal')content=<div className="dashboard-grid">{activity}<section className="panel daily-panel"><div className="panel-head"><h2>Your journal</h2><Icon name="book"/></div><div className="small-stat"><strong>{journals.length}</strong><span>saved entries</span></div><p>Use a daily entry for intentions, events, and lessons. Other journal notes can have any title.</p>{start('journal',today,'Write an entry')}</section></div>;
 if(page==='founder'){
  const open=taskRows([...group('founder'),...projects]).filter(t=>!t.done);
  content=<><div className="dashboard-grid"><section className="panel"><div className="panel-head"><h2>Open actions</h2><span className="pill">{open.length} remaining</span></div>{open.length?open.slice(0,4).map((t,i)=><div className="task-row" key={i}><span className="task-marker" aria-hidden="true"/><a href={linkTo(t.note)}>{t.text}<small>{title(t.note)}</small></a></div>):<div className="empty-message"><p>No open actions yet. Add a checklist to a project or founder note.</p>{start('founder','','Write priorities')}</div>}</section><section className="panel daily-panel"><div className="panel-head"><h2>Decisions and direction</h2><Icon name="compass"/></div><p>Record the decision, the reason, and the next action in a founder note.</p>{group('founder').length?group('founder').slice(0,2).map(row):<p>No founder notes yet.</p>}{start('founder','','Write a founder note')}</section></div>{shortcuts}</>;
 }
 if(page==='knowledge')content=<div className="dashboard-grid"><section className="panel"><div className="panel-head"><h2>Knowledge library</h2><Icon name="network"/></div><div className="knowledge-summary"><div className="knowledge-symbol"><Icon name="network"/></div><div><strong>{knowledge.length}</strong><p>notes with {knowledge.reduce((sum,n)=>sum+noteLinks(n).length,0)} outgoing links</p></div></div><div className="panel-foot"><span>Connect ideas with [[Note title]]</span>{start('knowledge','','Add a note')}</div></section><section className="panel"><div className="panel-head"><h2>Inbox</h2><span className="pill">{inbox.length} {inbox.length===1?'note':'notes'}</span></div><p>Capture ideas here before choosing where they belong.</p>{inbox.length?inbox.slice(0,2).map(row):<p>Your inbox is empty.</p>}{start('inbox','','Capture an idea')}</section></div>;
 if(page==='projects')content=<div className="project-grid">{projects.slice(0,6).map(n=>{const ts=taskRows([n]),done=ts.filter(t=>t.done).length;return <a key={n.path} className="panel project-card" href={linkTo(n)}><div className="panel-head"><Icon name="layers"/><span className="pill">{ts.length&&done===ts.length?'Checklist complete':'Project note'}</span></div><h2>{title(n)}</h2><p>{excerpt(n).slice(0,120)}</p><progress max={ts.length||1} value={done} aria-label={`${title(n)} checklist completion`}/><small>{done} of {ts.length} actions complete</small></a>;})}<section className="panel project-card placeholder"><div className="panel-head"><Icon name="plus"/><span className="pill">New project</span></div><h2>Define the next project</h2><p>Start with an outcome and a short list of actions.</p>{start('projects','','Create project')}</section></div>;
 if(page==='review'){
  const entries=journals.filter(n=>{const key=n.path.split('/')[1].slice(0,10);return key>=week&&key<=today;});
  content=<div className="dashboard-grid"><section className="panel daily-panel"><div className="panel-head"><h2>Week of {week}</h2><Icon name="check"/></div><div className="review-prompts"><div className="review-prompt"><Icon name="check"/>What did you finish?</div><div className="review-prompt"><Icon name="compass"/>What needs to change?</div><div className="review-prompt"><Icon name="layers"/>What will you prioritize next week?</div></div>{start('reviews',`Week of ${week}`,'Write weekly review')}</section><section className="panel"><div className="panel-head"><h2>Entries to review</h2><span className="pill">{entries.length} {entries.length===1?'entry':'entries'}</span></div>{entries.length?entries.slice(0,4).map(row):<p>No dated entries this week. You can still write a review.</p>}</section></div>;
 }
 const f=reviewFindings(notes,today);
 const checks:[string,({note:Note;text:string}|Note)[]][]=page==='today'?[['Due today',f.dueToday],['Overdue tasks',f.overdue]]:page==='founder'?[['Overdue and upcoming payments',f.payments],['Projects to review',f.stalled]]:page==='review'?[['Unfinished daily tasks',f.dailyStrays],['Overdue tasks',f.overdue],['Projects to review',f.stalled],['Overdue and upcoming payments',f.payments],['People last contacted over 30 days ago',f.contacts]]:[];
 return <>{content}{checks.length>0&&<div className="dashboard-grid">{checks.map(([label,items])=><section className="panel" key={label}><div className="panel-head"><h2>{label}</h2><span className="pill">{items.length}</span></div>{label==='Overdue and upcoming payments'?<p>Includes overdue payments and payments due within 14 days.</p>:label==='Projects to review'?<p>Active projects with no open actions or no file edits in 14 days.</p>:null}{items.length?items.slice(0,8).map((item,i)=>'note' in item?<div className="task-row" key={i}><a href={linkTo(item.note)}>{item.text}<small>{title(item.note)}</small></a></div>:row(item)):<p>No matching notes or tasks.</p>}{items.length>8&&<p>Showing the first 8 matches. Search all notes for more.</p>}</section>)}</div>}</>;
}
