import type { ReactNode } from 'react';
import { Icon } from './Icon';
import { GoalSummary,LeadFollowUps,Pipeline,Validation } from './Goal';
import { dateKey,now,today,monday,week,title,excerpt,linkTo,noteLinks,scoped } from './notes';
import { taskRows as rawTasks, reviewFindings } from '../shared/vault-model.js';
import type { Note } from './types';

const taskRows=rawTasks as (notes:Note[])=>{done:boolean;text:string;note:Note;due:string|null}[];
const muted='text-base-content/70';
function Panel({title,aside,className='',children}:{title:string;aside?:ReactNode;className?:string;children:ReactNode}){return <section className={'panel card min-w-0 border border-base-300 bg-base-200 '+className}><div className="card-body"><div className="panel-head mb-2 flex items-center justify-between gap-3"><h2>{title}</h2>{aside}</div>{children}</div></section>;}
const Count=({children,tone=''}:{children:ReactNode;tone?:string})=><span className={'pill badge badge-soft '+tone}>{children}</span>;
const Grid=({children}:{children:ReactNode})=><div className="dashboard-grid grid grid-cols-1 gap-6 lg:grid-cols-[minmax(0,1.65fr)_minmax(0,1fr)]">{children}</div>;
export function Overview({notes,page,onNew}:{notes:Note[];page:string;onNew:(kind:string,name?:string,opener?:HTMLElement,template?:string)=>void}) {
 const group=(folder:string)=>notes.filter(n=>n.path.startsWith(folder+'/'));
 const projects=group('projects'),journals=group('journal'),knowledge=group('knowledge'),inbox=group('inbox'),daily=notes.find(n=>n.path===`journal/${today}.md`);
 const row=(n:Note)=><a key={n.path} className="note-row flex min-h-11 items-start gap-3 border-b border-base-300 py-3 text-sm last:border-0 hover:underline" href={linkTo(n)}><span className="text-primary"><Icon name="file"/></span><span className="min-w-0 break-words">{title(n)}<small className={'mt-1 block text-xs '+muted}>{n.path.split('/')[0]} / {new Date(n.modified).toLocaleDateString()}</small></span></a>;
 const start=(kind:string,name:string,label:string,template?:string)=><button type="button" className="btn btn-outline btn-sm self-start" onClick={e=>onNew(kind,name,e.currentTarget,template)}>{label}</button>;
 const quick=(url:string,name:string,detail:string,type:string)=><a className="quick-card card card-sm border border-base-300 bg-base-200 hover:border-primary" href={scoped(url)}><div className="card-body flex-row items-center gap-3"><span className="grid size-12 shrink-0 place-items-center rounded-field bg-base-300 text-primary"><Icon name={type}/></span><span className="min-w-0"><strong className="block text-sm font-semibold">{name}</strong><small className={'block text-xs '+muted}>{detail}</small></span><span className={'ml-auto '+muted}><Icon name="arrow"/></span></div></a>;
 const days=Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(d.getDate()+i);const key=dateKey(d);return {d,key,saved:notes.some(n=>n.path===`journal/${key}.md`)};});
 const activity=<Panel title="This week" aside={<a className="link text-sm" href={scoped('/review')}>Review week</a>}><div className="week-strip">{days.map(({d,key,saved})=><div key={key} className={'day flex min-h-16 flex-col items-center justify-center gap-1 rounded-field border text-xs '+(key===today?'current border-primary text-primary':'border-transparent bg-base-100 '+muted)+(saved?' has-entry':'')} aria-label={`${key}, ${saved?'entry saved':'no dated entry'}`}><span>{d.toLocaleDateString('en',{weekday:'short'})}</span><strong className="text-sm">{d.getDate()}</strong><span className={'status '+(saved?'status-success':'')} aria-hidden="true"/></div>)}</div><p className="mt-4 flex items-baseline gap-2"><strong className="text-xl whitespace-nowrap">{days.filter(d=>d.saved).length} / 7</strong><span className={'text-xs '+muted}>days with a dated journal entry · Week of {week}</span></p></Panel>;
 const dailyPanel=<Panel className="daily-panel" title="Daily entry" aside={<Count tone={daily?'badge-success':''}>{daily?'Saved':'Not started'}</Count>}><div className="flex items-start gap-4"><div className="date-tile grid min-w-16 shrink-0 place-items-center rounded-field border border-base-300 bg-base-100 p-2 text-center"><span className={'text-xs '+muted}>{now.toLocaleDateString('en',{month:'short'})}</span><strong className="text-3xl font-semibold">{now.getDate()}</strong></div><div className="min-w-0"><h3 className="mb-2">{daily?"Continue today's entry":"Write today's entry"}</h3><p className={'mb-4 text-sm leading-relaxed break-words '+muted}>{daily?excerpt(daily).slice(0,180):'Set an intention, record what happened, and note what you learned.'}</p>{daily?<a className="btn btn-outline btn-sm" href={linkTo(daily)}>Open entry <Icon name="arrow"/></a>:start('journal',today,'Start daily entry')}</div></div></Panel>;
 const shortcuts=<div className="quick-actions mt-6 grid grid-cols-1 gap-4 md:grid-cols-3">{quick('/projects','Projects',`${projects.length} project notes`,'layers')}{quick('/knowledge','Knowledge',`${knowledge.length} ${knowledge.length===1?'note':'notes'} in your library`,'network')}{quick('/review','Weekly review','Review entries and next actions','check')}</div>;
 let content:ReactNode;
 if(page==='today')content=<><GoalSummary notes={notes} onNew={onNew}/><Grid>{dailyPanel}{activity}</Grid>{shortcuts}</>;
 if(page==='journal')content=<Grid>{activity}<Panel className="daily-panel" title="Your journal" aside={<span className="text-primary"><Icon name="book"/></span>}><p className="flex items-baseline gap-2"><strong className="text-xl">{journals.length}</strong><span className={'text-xs '+muted}>saved entries</span></p><p className={'text-sm leading-relaxed '+muted}>Use a daily entry for intentions, events, and lessons. Other journal notes can have any title.</p>{start('journal',today,'Write an entry')}</Panel></Grid>;
 if(page==='founder'){
  const open=taskRows([...group('founder'),...projects]).filter(t=>!t.done);
  content=<><div className="grid grid-cols-1 gap-6"><GoalSummary notes={notes} onNew={onNew}/><Pipeline notes={notes} onNew={onNew}/><Validation notes={notes} onNew={onNew}/></div><div className="mt-6"><Grid><Panel title="Open actions" aside={<Count>{open.length} remaining</Count>}>{open.length?open.slice(0,4).map((t,i)=><div className="task-row flex items-start gap-3 border-b border-base-300 py-3 text-sm last:border-0" key={i}><input type="checkbox" className="checkbox checkbox-sm mt-0.5" disabled aria-hidden="true" tabIndex={-1}/><a className="min-h-11 break-words hover:underline" href={linkTo(t.note)}>{t.text}<small className={'mt-1 block text-xs '+muted}>{title(t.note)}</small></a></div>):<div className="empty-message py-4"><p className={'mb-3 text-sm '+muted}>No open actions yet. Add a checklist to a project or founder note.</p>{start('founder','','Write priorities')}</div>}</Panel><Panel title="Decisions and direction" aside={<span className="text-primary"><Icon name="compass"/></span>}><p className={'text-sm leading-relaxed '+muted}>Record the decision, the reason, and the next action in a founder note.</p>{group('founder').length?group('founder').slice(0,2).map(row):<p className={'text-sm '+muted}>No founder notes yet.</p>}{start('founder','','Write a founder note')}</Panel></Grid></div>{shortcuts}</>;
 }
 if(page==='knowledge')content=<Grid><Panel title="Knowledge library" aside={<span className="text-primary"><Icon name="network"/></span>}><div className="knowledge-summary my-4 flex items-center gap-6"><span className="grid size-24 shrink-0 place-items-center rounded-full bg-base-300 text-primary"><Icon name="network"/></span><div><strong className="text-5xl font-semibold">{knowledge.length}</strong><p className={'text-sm '+muted}>notes with {knowledge.reduce((sum,n)=>sum+noteLinks(n).length,0)} outgoing links</p></div></div><div className={'flex flex-wrap items-center justify-between gap-4 border-t border-base-300 pt-4 text-xs '+muted}><span>Connect ideas with [[Note title]]</span>{start('knowledge','','Add a note')}</div></Panel><Panel title="Inbox" aside={<Count>{inbox.length} {inbox.length===1?'note':'notes'}</Count>}><p className={'text-sm '+muted}>Capture ideas here before choosing where they belong.</p>{inbox.length?inbox.slice(0,2).map(row):<p className={'text-sm '+muted}>Your inbox is empty.</p>}{start('inbox','','Capture an idea')}</Panel></Grid>;
 if(page==='projects')content=<div className="project-grid grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">{projects.slice(0,6).map(n=>{const ts=taskRows([n]),done=ts.filter(t=>t.done).length;return <a key={n.path} className="project-card card border border-base-300 bg-base-200 hover:border-primary" href={linkTo(n)}><div className="card-body"><div className="flex items-center justify-between gap-3"><span className="text-primary"><Icon name="layers"/></span><Count tone={ts.length&&done===ts.length?'badge-success':''}>{ts.length&&done===ts.length?'Checklist complete':'Project note'}</Count></div><h2 className="card-title">{title(n)}</h2><p className={'text-sm break-words '+muted}>{excerpt(n).slice(0,120)}</p><progress className="progress progress-primary" max={ts.length||1} value={done} aria-label={`${title(n)} checklist completion`}/><small className={'text-xs '+muted}>{done} of {ts.length} actions complete</small></div></a>;})}<section className="project-card placeholder card border border-dashed border-base-300"><div className="card-body"><div className="flex items-center justify-between gap-3"><span className="text-primary"><Icon name="plus"/></span><Count>New project</Count></div><h2 className="card-title">Define the next project</h2><p className={'text-sm '+muted}>Start with an outcome and a short list of actions.</p>{start('projects','','Create project')}</div></section></div>;
 if(page==='review'){
  const entries=journals.filter(n=>{const key=n.path.split('/')[1].slice(0,10);return key>=week&&key<=today;});
  content=<Grid><Panel className="daily-panel" title={`Week of ${week}`} aside={<span className="text-primary"><Icon name="check"/></span>}><ul className="review-prompts my-2 grid gap-3 text-sm">{[['check','What did you finish?'],['compass','What needs to change?'],['layers','What will you prioritize next week?'],['sun','Outreach, conversations, clients and MRR this week?']].map(([icon,text])=><li key={text} className="flex items-center gap-3"><span className="text-primary"><Icon name={icon}/></span>{text}</li>)}</ul><div className="flex flex-wrap gap-2">{start('reviews',`Week of ${week}`,'Write weekly review')}{start('reviews','Q4 2026 review','Write quarterly review','quarterly')}</div></Panel><Panel title="Entries to review" aside={<Count>{entries.length} {entries.length===1?'entry':'entries'}</Count>}>{entries.length?entries.slice(0,4).map(row):<p className={'text-sm '+muted}>No dated entries this week. You can still write a review.</p>}</Panel></Grid>;
 }
 const f=reviewFindings(notes,today);
 const checks:[string,({note:Note;text:string}|Note)[]][]=page==='today'?[['Due today',f.dueToday],['Overdue tasks',f.overdue]]:page==='founder'?[['Overdue and upcoming payments',f.payments],['Projects to review',f.stalled]]:page==='review'?[['Unfinished daily tasks',f.dailyStrays],['Overdue tasks',f.overdue],['Projects to review',f.stalled],['Overdue and upcoming payments',f.payments],['People last contacted over 30 days ago',f.contacts]]:[];
 return <>{content}{(checks.length>0||page==='today')&&<div className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-2">{page==='today'&&<LeadFollowUps notes={notes}/>}{checks.map(([label,items])=><Panel key={label} title={label} aside={<Count>{items.length}</Count>}>{label==='Overdue and upcoming payments'?<p className={'text-sm '+muted}>Includes overdue payments and payments due within 14 days.</p>:label==='Projects to review'?<p className={'text-sm '+muted}>Active projects with no open actions or no file edits in 14 days.</p>:null}{items.length?items.slice(0,8).map((item,i)=>'note' in item?<div className="task-row border-b border-base-300 py-3 text-sm last:border-0" key={i}><a className="min-h-11 break-words hover:underline" href={linkTo(item.note)}>{item.text}<small className={'mt-1 block text-xs '+muted}>{title(item.note)}</small></a></div>:row(item)):<p className={'text-sm '+muted}>No matching notes or tasks.</p>}{items.length>8&&<p className={'text-sm '+muted}>Showing the first 8 matches. Search all notes for more.</p>}</Panel>)}</div>}</>;
}
